### PR TITLE
Update all learning objs

### PR DESCRIPTION
**Pull request by naupaka**
This is a combined PR for all of the learning objective changes made by @kariljordan.

### CODE REVIEW

**Comment by naupaka** [comment]
Comment on original PRs from @kariljordan:

 Learning objectives have been revised and approved by Naupaka to align with Data Carpentry's assessment efforts.

**Comment by kariljordan** [comment]
Hi @naupaka, checking in to see if anyone else has comments on these learning objectives. Are we ready to merge/commit the changes?

**Comment by naupaka** [comment]
I guess not. I'm good to merge unless you got any other feedback offline that we should incorporate. Let me know and if not, I'll merge the changes in.

**Comment by kariljordan** [comment]
Hi @naupaka. We haven't had any other feedback or changes, so we're good to go. Thank you so much.

**Comment by kariljordan** [comment]
Hi @naupaka, it doesn't look like the changes have been merged. Can you merge them?

**Comment by naupaka** [comment]
Was merged but I hadn't re-rendered the html from the Rmd. Just did that, should be updated now. Sorry for the oversight.

**Pull request merged**
