### PR TITLE
changes to R lessons from Harvard workshop

### PR DESCRIPTION
**Pull request by tracykteal**
Lesson updated using the metadata for the E. coli dataset for the lesson. Major contributions from @mistrm82

### CODE REVIEW

**Comment by fmichonneau** [comment]
Just from a quick glance, I noticed that some of the Emacs backup files are being committed:
- `_lessons/#01-intro-to-R.Rmd#`
- `_lessons/00-before-we-start.Rmd~`
- `00-before-we-start.Rmd~`
- `01-intro-to-R.Rmd~`

I also noticed that some of the lessons are modified from R-ecology but the commit history is not coming along. I don't have strong feelings about this and it might be too difficult to reattach the history at this point, but it seems we tried to preserve it when possible in the past so I'm mentioning it.

**Comment by tracykteal** [comment]
Thanks, I removed the emacs files. You're right that they are adapted from R-ecology and don't have the proper commit history, and that would be good to fix. @fmichonneau do you know how we might manage that across repos? This will continue to be an issue as we adapt materials from one domain to another.

**Comment by fmichonneau** [comment]
I don't know how we could deal with keeping lessons in sync across repositories. If we end up transitioning to travis to build the lessons, I could imagine that we could build the lessons by taking bits and pieces from several repositories more easily (following something similar to what Rich had done during the reproducible science hackathon at NESCent last December), but I don't know if setting up something like this would be worth it (i.e., more advantages than drawbacks).

**Comment by hlapp** [comment]
> You're right that they are adapted from R-ecology and don't have the proper commit history, and that would be good to fix. @fmichonneau do you know how we might manage that across repos?

Use git subtree?

BTW this now has merge conflicts. And I do agree that bringing the commit history along would be good. It's in some ways our form of attribution.

**Pull request merged**
